apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-privileged
spec:
  selector:
    matchLabels:
      app: ubuntu-privileged
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu-privileged
    spec:
      containers:
      - name: ubuntu-privileged
        image: nginx
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          #privileged: true
          #allowPrivilegeEscalation: true