apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-privileged
spec:
  selector:
    matchLabels:
      app: ubuntu-privileged
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu-privileged
    spec:
      containers:
      - name: ubuntu-privileged
        image: nginx
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false

          # Insecure configuration - Pod with priviledge
          #privileged: true

          # Secure configuration - Priviledge set to false
          privileged: false

          # Insecure configuration - Pod should not have Priviledge escalation
          #allowPrivilegeEscalation: true

          capabilities:
            drop:
              - ALL