apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my-app:1.0.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysecretpassword
        - name: API_KEY
          value: O7q8Q~hjUupf1s5JqmHIjnz6EHL_X06gzCyyabfD
